version: '2.5.0'
services:
  node:
    container_name: borough-market-node
    image: redmax45/borough-market-node:0.1
    restart: always    
    ports:
      - 80:3000
    depends_on:
      - "mongo"
    volumes:
      - ./:/code
    links:
      - mongo
    environment:
      - mongoURI=${mongoURI}
    networks:
      - borough-market-network
  mongo:
    container_name: borough-market-mongo
    image: redmax45/mongo:0.1
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks: 
      - borough-market-network
volumes:
  mongodb:

networks:
  borough-market-network:
    driver: bridge
