version: '2.5.0'
services:
  node:    
    container_name: borough-market-node
    image: borough-market-node
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/code
    environment:
      - mongoURI=${mongoURI}
  mongo:    
    container_name: borough-market-mongo      
    image: mongo    
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db             
volumes:
  mongodb: