version: '3.8'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/code
    environment:
      - mongoURI=${mongoURI}
  mongo:          
    image: mongo    
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db             
volumes:
  mongodb: