version: '3'
services:
  nginx:
    container_name: borough-market-nginx 
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:nginx-${CIRCLE_SHA1}
    ports:
      - 80:80
    command: [nginx-debug, "-g", "daemon off;"]
    links:
      - node 
    depends_on:
      - node   
    networks:
      - nginx_network
  node:
    container_name: borough-market-node    
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:node-${CIRCLE_SHA1}
    restart: always    
    ports:      
      - 3000:3000
    depends_on:
      - "mongo"
    volumes:
      - ./:/code
    links:
      - mongo
    environment:
      - mongoURI=${mongoURI}   
    networks:
      - nginx_network
      - borough-market-network
  mongo:
    container_name: borough-market-mongo
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:mongo-${CIRCLE_SHA1}
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks: 
      - borough-market-network
volumes:
  mongodb:

networks:
  borough-market-network:
    driver: bridge
  nginx_network:
    external: true 
