version: 2.1
orbs:
  aws-ecs: circleci/aws-ecs@3.2.0
  aws-cli: circleci/aws-cli@3.1.3
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION

  build-test:
    docker:
      - image: docker:22.06-rc-git
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.17
      - run:
          name: Download and install docker compose
          environment:
            COMPOSE_VERSION: "2.5.0"
          command: |
            apk update && apk upgrade && apk add curl  
            curl -L "https://github.com/docker/compose/releases/download/v${COMPOSE_VERSION}/docker-compose-linux-x86_64" -o ~/docker-compose  
            chmod +x ~/docker-compose  
            mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Configure mongoURI
          command: export mongoURI=${mongoURI}
      - run:
          name: Build images of services and Start all services declared in docker-compose.yml
          command: docker-compose up -d --build
      - run:
          name: Curl http://127.0.0.1/
          command: |

            npm start

  # STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1/)

  #             if [ $STATUS -eq 200 ]; then
  #               echo "success"
  #             fi
  tag-and-push-image-to-ecr:
    docker:
      - image: docker:22.06-rc-git
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.17
      - run:
          name: Download and install docker compose
          environment:
            COMPOSE_VERSION: "2.5.0"
          command: |
            apk update && apk upgrade && apk add curl  
            curl -L "https://github.com/docker/compose/releases/download/v${COMPOSE_VERSION}/docker-compose-linux-x86_64" -o ~/docker-compose  
            chmod +x ~/docker-compose  
            mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Build images of services declared in docker-compose.yml
          command: docker-compose build
      - run:
          name: Start all services declared in docker-compose.yml
          command: docker-compose up -d
      - run:
          name: Install awscli
          command: |
            apk --no-cache add py-pip
            pip install awscli
      - run:
          name: Configure aws credentials
          command: |
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY} --profile default
            aws configure set aws_secret_access_key ${AWS_ACCESS_SECRET} --profile default
            aws configure set region ${AWS_REGION} --profile default
      - run:
          name: Execute aws ecr get-login-password
          command: aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - run:
          name: Push node images to ecr
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then      
              docker tag ${AWS_RESOURCE_NAME_PREFIX}-node:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:node
              docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:node
            fi
      - run:
          name: Push mongo images to ecr
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then     
              docker tag mongo:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:mongo
              docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:mongo
            fi
      - run:
          name: Tear down
          command: docker-compose down -v

workflows:
  aws-credentials-validate:
    jobs:
      - aws-cli-cred-setup:
          context: aws

  build-and-deploy:
    jobs:
      - build-test:
          filters:
            branches:
              only:
                - master
      - tag-and-push-image-to-ecr:
          filters:
            branches:
              only:
                - master
          requires:
            - build-test

      # - aws-ecs/deploy-service-update:
      #     requires:
      #       - aws-cli-setup-and-push-image
      #     aws-region: AWS_REGION
      #     family: "${AWS_RESOURCE_NAME_PREFIX}-service"
      #     cluster: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
      #     container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}"
      #     verify-revision-is-deployed: true
      #     post-steps:
      #       - run:
      #           name: Test the deployment
      #           command: |
      #             TARGET_GROUP_ARN=$(aws ecs describe-services --cluster ${AWS_RESOURCE_NAME_PREFIX}-cluster --services ${AWS_RESOURCE_NAME_PREFIX}-service | jq -r '.services[0].loadBalancers[0].targetGroupArn')
      #             ELB_ARN=$(aws elbv2 describe-target-groups --target-group-arns $TARGET_GROUP_ARN | jq -r '.TargetGroups[0].LoadBalancerArns[0]')
      #             ELB_DNS_NAME=$(aws elbv2 describe-load-balancers --load-balancer-arns $ELB_ARN | jq -r '.LoadBalancers[0].DNSName')
      #             curl -s --retry 10 http://$ELB_DNS_NAME | grep "Welcome to nginx!"
